# Generated by Django 3.1.4 on 2020-12-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mavier', '0002_comment_like_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_id',
            new_name='commenter',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liker_id',
            new_name='liker',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='sharer_id',
            new_name='sharer',
        ),
    ]
