# Generated by Django 3.1.4 on 2020-12-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavier', '0003_auto_20201215_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='orginal_post', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='share_content',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='share_post_id',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
