# Generated by Django 3.1.4 on 2020-12-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mavier', '0004_auto_20201216_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_posted',
            new_name='date_posted',
        ),
    ]
