# Generated by Django 3.1.4 on 2020-12-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavier', '0005_auto_20201216_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='like_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='share_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
