# Generated by Django 3.1.4 on 2020-12-16 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mavier', '0006_auto_20201216_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='share_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='share_post_id',
        ),
        migrations.CreateModel(
            name='SharedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_counter', models.IntegerField()),
                ('comment_counter', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mavier.post')),
            ],
        ),
    ]
