# Generated by Django 3.1.4 on 2020-12-17 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mavier', '0007_auto_20201216_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(help_text='First Name', max_length=32)),
                ('last_name', models.CharField(help_text='Last Name', max_length=32)),
                ('country_of_residence', models.CharField(help_text='Country of Residence', max_length=32)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], max_length=1, null=True)),
                ('relationship_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Un_Married', 'Un_Married'), ('In_A_Relation', 'In_A_Relation'), ('Complicated', 'Complicated'), ('single', 'single')], max_length=20, null=True)),
                ('profession', models.CharField(blank=True, help_text='Profession', max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
