# Generated by Django 3.1.4 on 2020-12-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mavier', '0009_auto_20201217_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
