# Generated by Django 3.1.4 on 2020-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavier', '0012_auto_20201228_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(default='This is generic Comment'),
            preserve_default=False,
        ),
    ]
