# Generated by Django 3.1.4 on 2020-12-29 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mavier', '0015_sharedpost_temp_like_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, choices=[('Post_Like', 'Post Like'), ('SharedPost_Like', 'SharedPost Like'), ('Post_Comment', 'Post Comment'), ('SharedPost_Comment', 'SharedPost Comment'), ('Post_Shared', 'Post_Shared'), ('New_Follower', 'New_Follower')], max_length=100, null=True)),
                ('notification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_message', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
