# Generated by Django 3.1.4 on 2020-12-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavier', '0017_auto_20201229_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link_variable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
