# Generated by Django 3.1.4 on 2020-12-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mavier', '0018_notifications_link_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='sharedPOST',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mavier.sharedpost'),
        ),
    ]
