# Generated by Django 3.1.4 on 2020-12-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201227_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Un_Married', 'Un Married'), ('In_A_Relation', 'In A Relation'), ('Complicated', 'Complicated'), ('single', 'Single')], max_length=20, null=True),
        ),
    ]
