# Generated by Django 3.1.4 on 2020-12-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201227_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country_of_residence',
            field=models.CharField(help_text='Country of Residence', max_length=32, null=True),
        ),
    ]
